# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c391b5f07b9889301976fe0f84ff9707acb80384dc06240697adaae0e1c14851ad16d1d3d93e5cf074e718ebb942b284e40d613961cad514414b85c2742611bc

test:
  secret_key_base: b008f5d0205f388520826b9aaabdb712409463fe4b231bea9b032bf33031b02b7a7b9869e6468ec2be6c975260dd02e0f3ae6a43b59d9784665ed69df4b115aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
